
import type { Metadata } from "next";
import { ErrorWrapper } from "./error-wrapper";

export const metadata: Metadata = {
  title: {
    default: "Main Page Next.js App",
    template:"%s | Kirit",
    absolute:"",

  },
  description: "Generated by create Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body> 
        <header style ={{ backgroundColor: "lightblue", padding: "1rem" }}>
          <h1>Header</h1>
        </header>
        <ErrorWrapper>
        {children}
        </ErrorWrapper>
        <footer style ={{ backgroundColor: "lightblue", padding: "1rem" }}>
          <h1>Footer</h1>
        </footer>
      </body>
    </html>
  );
}
