import type { Metadata } from "next";
import "./globals.css"; 
export const metadata: Metadata = {
  title: {
    default: "Main Page Next.js App",
    template: "%s | Kirit",
    absolute: "",
  },
  description: "Generated by create Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <header style={{ backgroundColor: "lightblue", padding: "1rem" }}>
          {/* Added classes text-3xl and font-bold */}
          <h1 className="text-3xl font-bold">Header</h1>
        </header>
        
        {children}
        
        <footer style={{ backgroundColor: "lightblue", padding: "1rem" }}>
          {/* Added classes text-3xl and font-bold */}
          <h1 className="text-3xl font-bold">Footer</h1>
        </footer>
      </body>
    </html>
  );
}